# Application name (used in Eureka)
spring:
  application:
    name: api-gateway

  # === Gateway discovery settings ===
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        # User Service Routes
        - id: user-service
          uri: http://localhost:8081  # Assuming your user service runs on port 8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        # Auth Service Routes (for future use)
        - id: auth-service
          uri: http://localhost:8082  # Assuming your auth service will run on port 8082
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

  # === Security (JWT) settings ===
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/.well-known/jwks.json

# === Eureka client settings ===
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Port on which the API Gateway will run
server:
  port: 8888

# Logging configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
