CREATE TABLE IF NOT EXISTS movie (
   id BIGINT AUTO_INCREMENT PRIMARY KEY,
   title VARCHAR(255) NOT NULL,
   duration_minutes INTEGER NOT NULL,
   director VARCHAR(255) NOT NULL,
   release_date DATE NOT NULL,
   country VARCHAR(255) NOT NULL,
   age_rating INTEGER NOT NULL
);